//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Spices_pos.CounterSalesInfo.CustomerSalesReport {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("cus_sales")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class cus_sales : global::System.Data.DataSet {
        
        private cus_salesDataTable tablecus_sales;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public cus_sales() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected cus_sales(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["cus_sales"] != null)) {
                    base.Tables.Add(new cus_salesDataTable(ds.Tables["cus_sales"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public cus_salesDataTable _cus_sales {
            get {
                return this.tablecus_sales;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            cus_sales cln = ((cus_sales)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["cus_sales"] != null)) {
                    base.Tables.Add(new cus_salesDataTable(ds.Tables["cus_sales"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tablecus_sales = ((cus_salesDataTable)(base.Tables["cus_sales"]));
            if ((initTable == true)) {
                if ((this.tablecus_sales != null)) {
                    this.tablecus_sales.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        private void InitClass() {
            this.DataSetName = "cus_sales";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/cus_sales.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tablecus_sales = new cus_salesDataTable();
            base.Tables.Add(this.tablecus_sales);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        private bool ShouldSerialize_cus_sales() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            cus_sales ds = new cus_sales();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public delegate void cus_salesRowChangeEventHandler(object sender, cus_salesRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class cus_salesDataTable : global::System.Data.TypedTableBase<cus_salesRow> {
            
            private global::System.Data.DataColumn columnfull_name;
            
            private global::System.Data.DataColumn columnExpr1;
            
            private global::System.Data.DataColumn columnbillNo;
            
            private global::System.Data.DataColumn columndate;
            
            private global::System.Data.DataColumn columnno_of_items;
            
            private global::System.Data.DataColumn columntotal_qty;
            
            private global::System.Data.DataColumn columnsub_total;
            
            private global::System.Data.DataColumn columndiscount;
            
            private global::System.Data.DataColumn columntax;
            
            private global::System.Data.DataColumn columnamount_due;
            
            private global::System.Data.DataColumn columnpaid;
            
            private global::System.Data.DataColumn columncredits;
            
            private global::System.Data.DataColumn columnpCredits;
            
            private global::System.Data.DataColumn columnstatus;
            
            private global::System.Data.DataColumn columnprod_name;
            
            private global::System.Data.DataColumn columnbarcode;
            
            private global::System.Data.DataColumn columnquantity;
            
            private global::System.Data.DataColumn columnpkg;
            
            private global::System.Data.DataColumn columnfull_pkg;
            
            private global::System.Data.DataColumn columnTotal_price;
            
            private global::System.Data.DataColumn columnpur_price;
            
            private global::System.Data.DataColumn columnsale_price;
            
            private global::System.Data.DataColumn columnmarket_value;
            
            private global::System.Data.DataColumn columnnote;
            
            private global::System.Data.DataColumn columntotal_taxation;
            
            private global::System.Data.DataColumn columntotal_marketPrice;
            
            private global::System.Data.DataColumn columninvoiceBarcode;
            
            private global::System.Data.DataColumn columncheck_sale_status;
            
            private global::System.Data.DataColumn columncredit_card_amount;
            
            private global::System.Data.DataColumn columnpaypal_amount;
            
            private global::System.Data.DataColumn columngoogle_pay_amount;
            
            private global::System.Data.DataColumn columnperItemDiscount;
            
            private global::System.Data.DataColumn columncustomerPoints;
            
            private global::System.Data.DataColumn columnbalance_amount;
            
            private global::System.Data.DataColumn columnsurcharges;
            
            private global::System.Data.DataColumn columnadvance_payment;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public cus_salesDataTable() {
                this.TableName = "cus_sales";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            internal cus_salesDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected cus_salesDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn full_nameColumn {
                get {
                    return this.columnfull_name;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn Expr1Column {
                get {
                    return this.columnExpr1;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn billNoColumn {
                get {
                    return this.columnbillNo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn dateColumn {
                get {
                    return this.columndate;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn no_of_itemsColumn {
                get {
                    return this.columnno_of_items;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn total_qtyColumn {
                get {
                    return this.columntotal_qty;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn sub_totalColumn {
                get {
                    return this.columnsub_total;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn discountColumn {
                get {
                    return this.columndiscount;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn taxColumn {
                get {
                    return this.columntax;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn amount_dueColumn {
                get {
                    return this.columnamount_due;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn paidColumn {
                get {
                    return this.columnpaid;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn creditsColumn {
                get {
                    return this.columncredits;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn pCreditsColumn {
                get {
                    return this.columnpCredits;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn statusColumn {
                get {
                    return this.columnstatus;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn prod_nameColumn {
                get {
                    return this.columnprod_name;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn barcodeColumn {
                get {
                    return this.columnbarcode;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn quantityColumn {
                get {
                    return this.columnquantity;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn pkgColumn {
                get {
                    return this.columnpkg;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn full_pkgColumn {
                get {
                    return this.columnfull_pkg;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn Total_priceColumn {
                get {
                    return this.columnTotal_price;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn pur_priceColumn {
                get {
                    return this.columnpur_price;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn sale_priceColumn {
                get {
                    return this.columnsale_price;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn market_valueColumn {
                get {
                    return this.columnmarket_value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn noteColumn {
                get {
                    return this.columnnote;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn total_taxationColumn {
                get {
                    return this.columntotal_taxation;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn total_marketPriceColumn {
                get {
                    return this.columntotal_marketPrice;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn invoiceBarcodeColumn {
                get {
                    return this.columninvoiceBarcode;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn check_sale_statusColumn {
                get {
                    return this.columncheck_sale_status;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn credit_card_amountColumn {
                get {
                    return this.columncredit_card_amount;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn paypal_amountColumn {
                get {
                    return this.columnpaypal_amount;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn google_pay_amountColumn {
                get {
                    return this.columngoogle_pay_amount;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn perItemDiscountColumn {
                get {
                    return this.columnperItemDiscount;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn customerPointsColumn {
                get {
                    return this.columncustomerPoints;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn balance_amountColumn {
                get {
                    return this.columnbalance_amount;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn surchargesColumn {
                get {
                    return this.columnsurcharges;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn advance_paymentColumn {
                get {
                    return this.columnadvance_payment;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public cus_salesRow this[int index] {
                get {
                    return ((cus_salesRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event cus_salesRowChangeEventHandler cus_salesRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event cus_salesRowChangeEventHandler cus_salesRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event cus_salesRowChangeEventHandler cus_salesRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event cus_salesRowChangeEventHandler cus_salesRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void Addcus_salesRow(cus_salesRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public cus_salesRow Addcus_salesRow(byte[] invoiceBarcode, double credit_card_amount, double paypal_amount, double google_pay_amount, double perItemDiscount, string customerPoints, string balance_amount, double surcharges, double advance_payment) {
                cus_salesRow rowcus_salesRow = ((cus_salesRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        invoiceBarcode,
                        null,
                        credit_card_amount,
                        paypal_amount,
                        google_pay_amount,
                        perItemDiscount,
                        customerPoints,
                        balance_amount,
                        surcharges,
                        advance_payment};
                rowcus_salesRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowcus_salesRow);
                return rowcus_salesRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                cus_salesDataTable cln = ((cus_salesDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new cus_salesDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            internal void InitVars() {
                this.columnfull_name = base.Columns["full_name"];
                this.columnExpr1 = base.Columns["Expr1"];
                this.columnbillNo = base.Columns["billNo"];
                this.columndate = base.Columns["date"];
                this.columnno_of_items = base.Columns["no_of_items"];
                this.columntotal_qty = base.Columns["total_qty"];
                this.columnsub_total = base.Columns["sub_total"];
                this.columndiscount = base.Columns["discount"];
                this.columntax = base.Columns["tax"];
                this.columnamount_due = base.Columns["amount_due"];
                this.columnpaid = base.Columns["paid"];
                this.columncredits = base.Columns["credits"];
                this.columnpCredits = base.Columns["pCredits"];
                this.columnstatus = base.Columns["status"];
                this.columnprod_name = base.Columns["prod_name"];
                this.columnbarcode = base.Columns["barcode"];
                this.columnquantity = base.Columns["quantity"];
                this.columnpkg = base.Columns["pkg"];
                this.columnfull_pkg = base.Columns["full_pkg"];
                this.columnTotal_price = base.Columns["Total_price"];
                this.columnpur_price = base.Columns["pur_price"];
                this.columnsale_price = base.Columns["sale_price"];
                this.columnmarket_value = base.Columns["market_value"];
                this.columnnote = base.Columns["note"];
                this.columntotal_taxation = base.Columns["total_taxation"];
                this.columntotal_marketPrice = base.Columns["total_marketPrice"];
                this.columninvoiceBarcode = base.Columns["invoiceBarcode"];
                this.columncheck_sale_status = base.Columns["check_sale_status"];
                this.columncredit_card_amount = base.Columns["credit_card_amount"];
                this.columnpaypal_amount = base.Columns["paypal_amount"];
                this.columngoogle_pay_amount = base.Columns["google_pay_amount"];
                this.columnperItemDiscount = base.Columns["perItemDiscount"];
                this.columncustomerPoints = base.Columns["customerPoints"];
                this.columnbalance_amount = base.Columns["balance_amount"];
                this.columnsurcharges = base.Columns["surcharges"];
                this.columnadvance_payment = base.Columns["advance_payment"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            private void InitClass() {
                this.columnfull_name = new global::System.Data.DataColumn("full_name", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfull_name);
                this.columnExpr1 = new global::System.Data.DataColumn("Expr1", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnExpr1);
                this.columnbillNo = new global::System.Data.DataColumn("billNo", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnbillNo);
                this.columndate = new global::System.Data.DataColumn("date", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columndate);
                this.columnno_of_items = new global::System.Data.DataColumn("no_of_items", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnno_of_items);
                this.columntotal_qty = new global::System.Data.DataColumn("total_qty", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columntotal_qty);
                this.columnsub_total = new global::System.Data.DataColumn("sub_total", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnsub_total);
                this.columndiscount = new global::System.Data.DataColumn("discount", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columndiscount);
                this.columntax = new global::System.Data.DataColumn("tax", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columntax);
                this.columnamount_due = new global::System.Data.DataColumn("amount_due", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnamount_due);
                this.columnpaid = new global::System.Data.DataColumn("paid", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnpaid);
                this.columncredits = new global::System.Data.DataColumn("credits", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncredits);
                this.columnpCredits = new global::System.Data.DataColumn("pCredits", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnpCredits);
                this.columnstatus = new global::System.Data.DataColumn("status", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnstatus);
                this.columnprod_name = new global::System.Data.DataColumn("prod_name", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnprod_name);
                this.columnbarcode = new global::System.Data.DataColumn("barcode", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnbarcode);
                this.columnquantity = new global::System.Data.DataColumn("quantity", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnquantity);
                this.columnpkg = new global::System.Data.DataColumn("pkg", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnpkg);
                this.columnfull_pkg = new global::System.Data.DataColumn("full_pkg", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfull_pkg);
                this.columnTotal_price = new global::System.Data.DataColumn("Total_price", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTotal_price);
                this.columnpur_price = new global::System.Data.DataColumn("pur_price", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnpur_price);
                this.columnsale_price = new global::System.Data.DataColumn("sale_price", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnsale_price);
                this.columnmarket_value = new global::System.Data.DataColumn("market_value", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnmarket_value);
                this.columnnote = new global::System.Data.DataColumn("note", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnnote);
                this.columntotal_taxation = new global::System.Data.DataColumn("total_taxation", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columntotal_taxation);
                this.columntotal_marketPrice = new global::System.Data.DataColumn("total_marketPrice", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columntotal_marketPrice);
                this.columninvoiceBarcode = new global::System.Data.DataColumn("invoiceBarcode", typeof(byte[]), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columninvoiceBarcode);
                this.columncheck_sale_status = new global::System.Data.DataColumn("check_sale_status", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncheck_sale_status);
                this.columncredit_card_amount = new global::System.Data.DataColumn("credit_card_amount", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncredit_card_amount);
                this.columnpaypal_amount = new global::System.Data.DataColumn("paypal_amount", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnpaypal_amount);
                this.columngoogle_pay_amount = new global::System.Data.DataColumn("google_pay_amount", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columngoogle_pay_amount);
                this.columnperItemDiscount = new global::System.Data.DataColumn("perItemDiscount", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnperItemDiscount);
                this.columncustomerPoints = new global::System.Data.DataColumn("customerPoints", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncustomerPoints);
                this.columnbalance_amount = new global::System.Data.DataColumn("balance_amount", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnbalance_amount);
                this.columnsurcharges = new global::System.Data.DataColumn("surcharges", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnsurcharges);
                this.columnadvance_payment = new global::System.Data.DataColumn("advance_payment", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnadvance_payment);
                this.columnfull_name.AutoIncrement = true;
                this.columnfull_name.AutoIncrementSeed = -1;
                this.columnfull_name.AutoIncrementStep = -1;
                this.columnfull_name.AllowDBNull = false;
                this.columnExpr1.AutoIncrement = true;
                this.columnExpr1.AutoIncrementSeed = -1;
                this.columnExpr1.AutoIncrementStep = -1;
                this.columnExpr1.AllowDBNull = false;
                this.columnbillNo.AutoIncrement = true;
                this.columnbillNo.AutoIncrementSeed = -1;
                this.columnbillNo.AutoIncrementStep = -1;
                this.columnbillNo.AllowDBNull = false;
                this.columndate.AutoIncrement = true;
                this.columndate.AutoIncrementSeed = -1;
                this.columndate.AutoIncrementStep = -1;
                this.columndate.AllowDBNull = false;
                this.columnno_of_items.AutoIncrement = true;
                this.columnno_of_items.AutoIncrementSeed = -1;
                this.columnno_of_items.AutoIncrementStep = -1;
                this.columnno_of_items.AllowDBNull = false;
                this.columntotal_qty.AutoIncrement = true;
                this.columntotal_qty.AutoIncrementSeed = -1;
                this.columntotal_qty.AutoIncrementStep = -1;
                this.columntotal_qty.AllowDBNull = false;
                this.columnsub_total.AutoIncrement = true;
                this.columnsub_total.AutoIncrementSeed = -1;
                this.columnsub_total.AutoIncrementStep = -1;
                this.columnsub_total.AllowDBNull = false;
                this.columndiscount.AutoIncrement = true;
                this.columndiscount.AutoIncrementSeed = -1;
                this.columndiscount.AutoIncrementStep = -1;
                this.columndiscount.AllowDBNull = false;
                this.columntax.AutoIncrement = true;
                this.columntax.AutoIncrementSeed = -1;
                this.columntax.AutoIncrementStep = -1;
                this.columntax.AllowDBNull = false;
                this.columnamount_due.AutoIncrement = true;
                this.columnamount_due.AutoIncrementSeed = -1;
                this.columnamount_due.AutoIncrementStep = -1;
                this.columnamount_due.AllowDBNull = false;
                this.columnpaid.AutoIncrement = true;
                this.columnpaid.AutoIncrementSeed = -1;
                this.columnpaid.AutoIncrementStep = -1;
                this.columnpaid.AllowDBNull = false;
                this.columncredits.AutoIncrement = true;
                this.columncredits.AutoIncrementSeed = -1;
                this.columncredits.AutoIncrementStep = -1;
                this.columncredits.AllowDBNull = false;
                this.columnpCredits.AutoIncrement = true;
                this.columnpCredits.AutoIncrementSeed = -1;
                this.columnpCredits.AutoIncrementStep = -1;
                this.columnpCredits.AllowDBNull = false;
                this.columnstatus.AutoIncrement = true;
                this.columnstatus.AutoIncrementSeed = -1;
                this.columnstatus.AutoIncrementStep = -1;
                this.columnstatus.AllowDBNull = false;
                this.columnprod_name.AutoIncrement = true;
                this.columnprod_name.AutoIncrementSeed = -1;
                this.columnprod_name.AutoIncrementStep = -1;
                this.columnprod_name.AllowDBNull = false;
                this.columnbarcode.AutoIncrement = true;
                this.columnbarcode.AutoIncrementSeed = -1;
                this.columnbarcode.AutoIncrementStep = -1;
                this.columnbarcode.AllowDBNull = false;
                this.columnquantity.AutoIncrement = true;
                this.columnquantity.AutoIncrementSeed = -1;
                this.columnquantity.AutoIncrementStep = -1;
                this.columnquantity.AllowDBNull = false;
                this.columnpkg.AutoIncrement = true;
                this.columnpkg.AutoIncrementSeed = -1;
                this.columnpkg.AutoIncrementStep = -1;
                this.columnpkg.AllowDBNull = false;
                this.columnfull_pkg.AutoIncrement = true;
                this.columnfull_pkg.AutoIncrementSeed = -1;
                this.columnfull_pkg.AutoIncrementStep = -1;
                this.columnfull_pkg.AllowDBNull = false;
                this.columnTotal_price.AutoIncrement = true;
                this.columnTotal_price.AutoIncrementSeed = -1;
                this.columnTotal_price.AutoIncrementStep = -1;
                this.columnTotal_price.AllowDBNull = false;
                this.columnpur_price.AutoIncrement = true;
                this.columnpur_price.AutoIncrementSeed = -1;
                this.columnpur_price.AutoIncrementStep = -1;
                this.columnpur_price.AllowDBNull = false;
                this.columnsale_price.AutoIncrement = true;
                this.columnsale_price.AutoIncrementSeed = -1;
                this.columnsale_price.AutoIncrementStep = -1;
                this.columnsale_price.AllowDBNull = false;
                this.columnmarket_value.AutoIncrement = true;
                this.columnmarket_value.AutoIncrementSeed = -1;
                this.columnmarket_value.AutoIncrementStep = -1;
                this.columnmarket_value.AllowDBNull = false;
                this.columnnote.AutoIncrement = true;
                this.columnnote.AutoIncrementSeed = -1;
                this.columnnote.AutoIncrementStep = -1;
                this.columnnote.AllowDBNull = false;
                this.columntotal_taxation.AutoIncrement = true;
                this.columntotal_taxation.AutoIncrementSeed = -1;
                this.columntotal_taxation.AutoIncrementStep = -1;
                this.columntotal_marketPrice.AutoIncrement = true;
                this.columntotal_marketPrice.AutoIncrementSeed = -1;
                this.columntotal_marketPrice.AutoIncrementStep = -1;
                this.columntotal_marketPrice.AllowDBNull = false;
                this.columninvoiceBarcode.AutoIncrementSeed = -1;
                this.columninvoiceBarcode.AutoIncrementStep = -1;
                this.columncheck_sale_status.AutoIncrement = true;
                this.columncheck_sale_status.AutoIncrementSeed = -1;
                this.columncheck_sale_status.AutoIncrementStep = -1;
                this.ExtendedProperties.Add("Generator_TablePropName", "_cus_sales");
                this.ExtendedProperties.Add("Generator_UserTableName", "cus_sales");
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public cus_salesRow Newcus_salesRow() {
                return ((cus_salesRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new cus_salesRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(cus_salesRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.cus_salesRowChanged != null)) {
                    this.cus_salesRowChanged(this, new cus_salesRowChangeEvent(((cus_salesRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.cus_salesRowChanging != null)) {
                    this.cus_salesRowChanging(this, new cus_salesRowChangeEvent(((cus_salesRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.cus_salesRowDeleted != null)) {
                    this.cus_salesRowDeleted(this, new cus_salesRowChangeEvent(((cus_salesRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.cus_salesRowDeleting != null)) {
                    this.cus_salesRowDeleting(this, new cus_salesRowChangeEvent(((cus_salesRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void Removecus_salesRow(cus_salesRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                cus_sales ds = new cus_sales();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "cus_salesDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class cus_salesRow : global::System.Data.DataRow {
            
            private cus_salesDataTable tablecus_sales;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            internal cus_salesRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tablecus_sales = ((cus_salesDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public int full_name {
                get {
                    return ((int)(this[this.tablecus_sales.full_nameColumn]));
                }
                set {
                    this[this.tablecus_sales.full_nameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public int Expr1 {
                get {
                    return ((int)(this[this.tablecus_sales.Expr1Column]));
                }
                set {
                    this[this.tablecus_sales.Expr1Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public int billNo {
                get {
                    return ((int)(this[this.tablecus_sales.billNoColumn]));
                }
                set {
                    this[this.tablecus_sales.billNoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public int date {
                get {
                    return ((int)(this[this.tablecus_sales.dateColumn]));
                }
                set {
                    this[this.tablecus_sales.dateColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public int no_of_items {
                get {
                    return ((int)(this[this.tablecus_sales.no_of_itemsColumn]));
                }
                set {
                    this[this.tablecus_sales.no_of_itemsColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public int total_qty {
                get {
                    return ((int)(this[this.tablecus_sales.total_qtyColumn]));
                }
                set {
                    this[this.tablecus_sales.total_qtyColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public int sub_total {
                get {
                    return ((int)(this[this.tablecus_sales.sub_totalColumn]));
                }
                set {
                    this[this.tablecus_sales.sub_totalColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public int discount {
                get {
                    return ((int)(this[this.tablecus_sales.discountColumn]));
                }
                set {
                    this[this.tablecus_sales.discountColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public int tax {
                get {
                    return ((int)(this[this.tablecus_sales.taxColumn]));
                }
                set {
                    this[this.tablecus_sales.taxColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public int amount_due {
                get {
                    return ((int)(this[this.tablecus_sales.amount_dueColumn]));
                }
                set {
                    this[this.tablecus_sales.amount_dueColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public int paid {
                get {
                    return ((int)(this[this.tablecus_sales.paidColumn]));
                }
                set {
                    this[this.tablecus_sales.paidColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public int credits {
                get {
                    return ((int)(this[this.tablecus_sales.creditsColumn]));
                }
                set {
                    this[this.tablecus_sales.creditsColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public int pCredits {
                get {
                    return ((int)(this[this.tablecus_sales.pCreditsColumn]));
                }
                set {
                    this[this.tablecus_sales.pCreditsColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public int status {
                get {
                    return ((int)(this[this.tablecus_sales.statusColumn]));
                }
                set {
                    this[this.tablecus_sales.statusColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public int prod_name {
                get {
                    return ((int)(this[this.tablecus_sales.prod_nameColumn]));
                }
                set {
                    this[this.tablecus_sales.prod_nameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public int barcode {
                get {
                    return ((int)(this[this.tablecus_sales.barcodeColumn]));
                }
                set {
                    this[this.tablecus_sales.barcodeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public int quantity {
                get {
                    return ((int)(this[this.tablecus_sales.quantityColumn]));
                }
                set {
                    this[this.tablecus_sales.quantityColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public int pkg {
                get {
                    return ((int)(this[this.tablecus_sales.pkgColumn]));
                }
                set {
                    this[this.tablecus_sales.pkgColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public int full_pkg {
                get {
                    return ((int)(this[this.tablecus_sales.full_pkgColumn]));
                }
                set {
                    this[this.tablecus_sales.full_pkgColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public int Total_price {
                get {
                    return ((int)(this[this.tablecus_sales.Total_priceColumn]));
                }
                set {
                    this[this.tablecus_sales.Total_priceColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public int pur_price {
                get {
                    return ((int)(this[this.tablecus_sales.pur_priceColumn]));
                }
                set {
                    this[this.tablecus_sales.pur_priceColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public int sale_price {
                get {
                    return ((int)(this[this.tablecus_sales.sale_priceColumn]));
                }
                set {
                    this[this.tablecus_sales.sale_priceColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public int market_value {
                get {
                    return ((int)(this[this.tablecus_sales.market_valueColumn]));
                }
                set {
                    this[this.tablecus_sales.market_valueColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public int note {
                get {
                    return ((int)(this[this.tablecus_sales.noteColumn]));
                }
                set {
                    this[this.tablecus_sales.noteColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public int total_taxation {
                get {
                    try {
                        return ((int)(this[this.tablecus_sales.total_taxationColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'total_taxation\' in table \'cus_sales\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablecus_sales.total_taxationColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public int total_marketPrice {
                get {
                    return ((int)(this[this.tablecus_sales.total_marketPriceColumn]));
                }
                set {
                    this[this.tablecus_sales.total_marketPriceColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public byte[] invoiceBarcode {
                get {
                    try {
                        return ((byte[])(this[this.tablecus_sales.invoiceBarcodeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'invoiceBarcode\' in table \'cus_sales\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablecus_sales.invoiceBarcodeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public int check_sale_status {
                get {
                    try {
                        return ((int)(this[this.tablecus_sales.check_sale_statusColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'check_sale_status\' in table \'cus_sales\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablecus_sales.check_sale_statusColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public double credit_card_amount {
                get {
                    try {
                        return ((double)(this[this.tablecus_sales.credit_card_amountColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'credit_card_amount\' in table \'cus_sales\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablecus_sales.credit_card_amountColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public double paypal_amount {
                get {
                    try {
                        return ((double)(this[this.tablecus_sales.paypal_amountColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'paypal_amount\' in table \'cus_sales\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablecus_sales.paypal_amountColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public double google_pay_amount {
                get {
                    try {
                        return ((double)(this[this.tablecus_sales.google_pay_amountColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'google_pay_amount\' in table \'cus_sales\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablecus_sales.google_pay_amountColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public double perItemDiscount {
                get {
                    try {
                        return ((double)(this[this.tablecus_sales.perItemDiscountColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'perItemDiscount\' in table \'cus_sales\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablecus_sales.perItemDiscountColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string customerPoints {
                get {
                    try {
                        return ((string)(this[this.tablecus_sales.customerPointsColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'customerPoints\' in table \'cus_sales\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablecus_sales.customerPointsColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string balance_amount {
                get {
                    try {
                        return ((string)(this[this.tablecus_sales.balance_amountColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'balance_amount\' in table \'cus_sales\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablecus_sales.balance_amountColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public double surcharges {
                get {
                    try {
                        return ((double)(this[this.tablecus_sales.surchargesColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'surcharges\' in table \'cus_sales\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablecus_sales.surchargesColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public double advance_payment {
                get {
                    try {
                        return ((double)(this[this.tablecus_sales.advance_paymentColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'advance_payment\' in table \'cus_sales\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablecus_sales.advance_paymentColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool Istotal_taxationNull() {
                return this.IsNull(this.tablecus_sales.total_taxationColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void Settotal_taxationNull() {
                this[this.tablecus_sales.total_taxationColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsinvoiceBarcodeNull() {
                return this.IsNull(this.tablecus_sales.invoiceBarcodeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetinvoiceBarcodeNull() {
                this[this.tablecus_sales.invoiceBarcodeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool Ischeck_sale_statusNull() {
                return this.IsNull(this.tablecus_sales.check_sale_statusColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void Setcheck_sale_statusNull() {
                this[this.tablecus_sales.check_sale_statusColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool Iscredit_card_amountNull() {
                return this.IsNull(this.tablecus_sales.credit_card_amountColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void Setcredit_card_amountNull() {
                this[this.tablecus_sales.credit_card_amountColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool Ispaypal_amountNull() {
                return this.IsNull(this.tablecus_sales.paypal_amountColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void Setpaypal_amountNull() {
                this[this.tablecus_sales.paypal_amountColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool Isgoogle_pay_amountNull() {
                return this.IsNull(this.tablecus_sales.google_pay_amountColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void Setgoogle_pay_amountNull() {
                this[this.tablecus_sales.google_pay_amountColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsperItemDiscountNull() {
                return this.IsNull(this.tablecus_sales.perItemDiscountColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetperItemDiscountNull() {
                this[this.tablecus_sales.perItemDiscountColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IscustomerPointsNull() {
                return this.IsNull(this.tablecus_sales.customerPointsColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetcustomerPointsNull() {
                this[this.tablecus_sales.customerPointsColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool Isbalance_amountNull() {
                return this.IsNull(this.tablecus_sales.balance_amountColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void Setbalance_amountNull() {
                this[this.tablecus_sales.balance_amountColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IssurchargesNull() {
                return this.IsNull(this.tablecus_sales.surchargesColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetsurchargesNull() {
                this[this.tablecus_sales.surchargesColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool Isadvance_paymentNull() {
                return this.IsNull(this.tablecus_sales.advance_paymentColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void Setadvance_paymentNull() {
                this[this.tablecus_sales.advance_paymentColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public class cus_salesRowChangeEvent : global::System.EventArgs {
            
            private cus_salesRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public cus_salesRowChangeEvent(cus_salesRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public cus_salesRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591